-- 산술 연산자

SELECT ENAME ,SAL , SAL * 1.1 -- 급여 10% 인상분
FROM T_EMP ;

SELECT ENAME ,SAL ,COMM, SAL + COMM -- null 값과의 산술연산은 무.조.건 NULL 입니다
FROM T_EMP ;

-- WHERE 조건절
SELECT * FROM T_EMP WHERE JOB = 'SALESMAN';
SELECT * FROM T_EMP WHERE JOB = 'SALESman'; -- 문장은 에러가아니여서 작동은하지만 문자열의 대소문자가구별이 안되어서 출력값이없음

SELECT ENAME ,SAL, DEPTNO 
FROM T_EMP
WHERE DEPTNO = 10;

--

SELECT ENAME ,EMPNO ,SAL 
FROM T_EMP 
WHERE ENAME = 'SCOTT';

SELECT NAME ,GRADE FROM T_STUDENT WHERE GRADE = 2 OR GRADE = 3;
SELECT NAME ,GRADE FROM T_STUDENT WHERE GRADE IN (2,3);
SELECT NAME ,GRADE FROM T_STUDENT WHERE GRADE > 1 AND GRADE < 4;
SELECT NAME ,GRADE FROM T_STUDENT WHERE GRADE NOT IN (1,4);
SELECT NAME ,GRADE FROM T_STUDENT WHERE GRADE BETWEEN 2 AND 3;

SELECT NAME ,PAY , POSITION FROM T_PROFESSOR WHERE PAY > 300;
SELECT NAME, POSITION FROM T_PROFESSOR WHERE BONUS IS NULL ;

--LIKE
--교수님 중에서 김씨성을가진 교수님의 이름만 출력 (LIKE 사용)
SELECT name FROM T_PROFESSOR WHERE NAME LIKE '김%'; -- %는 어떠한것도 와도된다 심지어 아무것도없어도 가능

SELECT ENAME 
FROM T_EMP 
WHERE ENAME LIKE '%NE%'

--직원테이블(t_emp)에서 직원이름 중에 두번째글자가 A 인 사람의 이름만 출력
SELECT ename FROM T_EMP WHERE ENAME LIKE '_A%' --  _는 반드시 무언가 와야합니다 하나라도

-----------------------------------------------------------------
-- ORDER BY 내림차순!
SELECT ename FROM T_EMP WHERE ENAME LIKE '%L%'
ORDER BY ENAME DESC; -- DESC 가 없으면 오름차순

SELECT ENAME ,JOB ,SAL 
FROM T_EMP 
ORDER BY JOB DESC, SAL ASC ; -- 안붙여도 되지만 ASC를붙여도 오름차순으로 정렬한다



SELECT
FROM T_STUDENT 