SELECT NAME 
FROM T_STUDENT 
WHERE HEIGHT > 180

SELECT NAME , WEIGHT 
FROM T_STUDENT 
WHERE WEIGHT > 60 AND WEIGHT < 80;

SELECT NAME 
FROM T_STUDENT 
WHERE DEPTNO1 IN (101,201)

SELECT NAME
FROM T_STUDENT 
WHERE NAME LIKE '김%'

--SELECT * FROM T_STUDENT;

SELECT NAME ,GRADE ,HEIGHT 
FROM T_STUDENT 
WHERE HEIGHT > 170

SELECT NAME ,GRADE ,WEIGHT 
FROM T_STUDENT 
WHERE WEIGHT >80 OR GRADE = 1

SELECT NAME , HEIGHT , WEIGHT 
FROM T_STUDENT 
WHERE GRADE = 2 AND WEIGHT >70 AND HEIGHT >180;

SELECT ENAME ,HIREDATE 
FROM T_EMP 
WHERE HIREDATE BETWEEN '1900-01-01' AND '1992-01-01'

SELECT NAME ,BIRTHDAY ,HEIGHT ,WEIGHT 
FROM T_STUDENT 
ORDER BY BIRTHDAY ;

SELECT NAME AS "이름" , HEIGHT AS "키"
FROM T_STUDENT 
ORDER BY NAME 

SELECT NAME ,BIRTHDAY 
FROM T_EMP2 
WHERE BIRTHDAY BETWEEN '1980-01-01' AND '1990-01-01'
