SELECT EMPNO ,ENAME ,SAL FROM T_EMP ;

--자동적으로 오라클에서 붙여주는 행번호 객체 (ROWNUM)
SELECT ROWNUM, EMPNO ,ENAME ,SAL FROM T_EMP ;

-- 순차를바꿔도 ROUNUM은 1부터 시작한다 / ROWNUM을 바꾸지않는다면
SELECT ROWNUM, EMPNO ,ENAME ,SAL FROM T_EMP ORDER BY EMPNO DESC ;

-- 상위 5개만 뽑기
SELECT ROWNUM, EMPNO ,ENAME ,SAL FROM T_EMP
WHERE ROWNUM < 5 ORDER BY EMPNO DESC ;

-- SELECT 에서 ROWNUM이 없어도 사용가능 (ORACLE에서 자동생성객체)
SELECT EMPNO ,ENAME ,SAL FROM T_EMP
WHERE ROWNUM <= 5 ORDER BY EMPNO DESC ;

-- ROWNUM > 5 동작안함 ROUNUM 범위가 1이 포함이 안되면 동작안함.
SELECT ROWNUM, EMPNO ,ENAME ,SAL FROM T_EMP WHERE ROWNUM > 5 ORDER BY EMPNO DESC ;

-- 상위 5개 출력
-- row1 ~ row5 까지 출력 ( 1page가 5개일때를 가정)
SELECT ROWNUM, EMPNO ,ENAME ,SAL
FROM T_EMP
WHERE ROWNUM >= 6 AND ROWNUM < 6+5 
ORDER BY EMPNO DESC ;

-- phonebook 뻥튀기
SELECT * FROM PHONEBOOK ;
INSERT INTO PHONEBOOK (SELECT * FROM PHONEBOOK ); -- Primary Key 중복 (유니크키값)

INSERT INTO phonebook 
	(SELECT phonebook_sql.nextval, PB_NAME , PB_PHONE , PB_MEMO , SYSDATE FROM PHONEBOOK );

-- ROWNUM rev.
SELECT pb_uid, pb_name, pb_phonenum FROM PHONEBOOK ORDER BY PB_UID DESC ;

SELECT T.*
FROM (SELECT pb_uid, pb_name, pb_phonenum FROM PHONEBOOK ORDER BY PB_UID DESC) T
;


SELECT ROWNUM AS RNUM, T.*
FROM (SELECT pb_uid, pb_name, pb_phonenum FROM PHONEBOOK ORDER BY PB_UID DESC) T
;

-- 한 페이지당 5개데이터
-- 3번째 페이지
SELECT * FROM
(
SELECT ROWNUM AS RNUM, T.*
FROM (SELECT pb_uid, pb_name, pb_phonenum FROM PHONEBOOK ORDER BY PB_UID DESC) T
)
WHERE RNUM >= 16 AND RNUM < 16 + 5;
