-- JOIN


-- FROM 절에 테이블에도 별칭(alias)를 줄 수 있다.

-- 20 레코드
SELECT s.STUDNO, s.NAME, s.DEPTNO1 
FROM T_STUDENT s;


-- 12 레코드
SELECT d.DEPTNO ,d.DNAME 
FROM T_DEPARTMENT d; 


-- 카티션곱 (Cartesian Product)
-- 두개의 테이블을 JOIN 하게 되면, 
-- 각 테이블의 레코드들의 모든 조합이 출력된다.
-- WHERE 나 ON 등으로 JOIN 조건이 주어지지 않으면 
-- 모든 카티션곱이 출력된다. 
SELECT s.STUDNO ,s.NAME ,s.DEPTNO1 ,
	d.DEPTNO , d.DNAME 
FROM T_STUDENT s, T_DEPARTMENT d; --Oracle 방식


SELECT s.STUDNO ,s.NAME ,s.DEPTNO1 ,
	d.DEPTNO , d.DNAME 
FROM T_STUDENT s CROSS JOIN T_DEPARTMENT d; --ANSI 방식


-- Equi Join (등가 조인)
-- Oracle Join 방식
SELECT s.NAME ,s.DEPTNO1 ,d.DNAME 
FROM T_STUDENT s, T_DEPARTMENT d
WHERE s.DEPTNO1 = d.DEPTNO;

-- ANSI 방식
SELECT s.NAME ,s.DEPTNO1 ,d.DNAME 
FROM T_STUDENT s JOIN T_DEPARTMENT d
ON s.DEPTNO1 = d.DEPTNO ; -- ON = JOIN 조건

-- 제 2전공은? deptno2
SELECT s.NAME "학생이름", s.DEPTNO2 "제2학과", d.DNAME "제2학과이름"
FROM T_STUDENT s, T_DEPARTMENT d
WHERE s.DEPTNO2  = d.DEPTNO;

-- #6102
SELECT * FROM T_DEPARTMENT ;

SELECT s.NAME ,s.PROFNO ,p.NAME 
FROM T_STUDENT s, T_PROFESSOR p
WHERE s.PROFNO = p.PROFNO;

SELECT s.NAME ,s.PROFNO ,p.NAME 
FROM T_STUDENT s JOIN T_PROFESSOR p
ON s.PROFNO = p.PROFNO;

-- #6103
SELECT s.NAME ,d.DNAME ,p.NAME 
FROM T_STUDENT s, T_PROFESSOR p, T_DEPARTMENT d
WHERE s.PROFNO = p.PROFNO AND s.DEPTNO1 = d.DEPTNO  ;

SELECT s.NAME , d.DNAME , p.NAME 
FROM T_STUDENT s JOIN T_PROFESSOR p ON s.PROFNO = p.PROFNO JOIN T_DEPARTMENT d ON s.DEPTNO1  = d.DEPTNO;

-- #6104
SELECT * FROM T_EMP2 ;
SELECT * FROM T_POST ;

SELECT e.NAME , e.POST , e.PAY ,e.PAY - p.S_PAY ,e.PAY +p.E_PAY 
FROM T_EMP2 e, T_POST p
WHERE e.POST = p.POST ;

SELECT e.NAME , e.POST , e.PAY ,p.S_PAY ,p.E_PAY 
FROM T_EMP2 e join T_POST p ON e.POST  = p.POST ;

-- #6105
SELECT * FROM T_STUDENT ;
SELECT * FROM T_PROFESSOR ;

SELECT s.NAME ,p.NAME 
FROM T_STUDENT s,T_PROFESSOR p
WHERE s.DEPTNO1 = 101 AND s.PROFNO = p.PROFNO ;

SELECT s.NAME ,p.NAME 
FROM T_STUDENT s JOIN T_PROFESSOR p ON s.PROFNO = p.PROFNO 
--FROM T_STUDENT s JOIN T_PROFESSOR p ON s.PROFNO = p.PROFNO AND s.DEPTINO1 = 101; 도 상관없다
WHERE s.DEPTNO1 = 101;
-- #6201
